// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePost = "posts"

// Post mapped from table <posts>
type Post struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int32     `gorm:"column:user_id" json:"user_id"`
	Tag         string    `gorm:"column:tag" json:"tag"`
	TopicsName  string    `gorm:"column:topics_name" json:"topics_name"`
	MdPlainText string    `gorm:"column:md_plain_text" json:"md_plain_text"`
	MdHTMLText  string    `gorm:"column:md_html_text" json:"md_html_text"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
