// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	ID  int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Tag string `gorm:"column:tag" json:"tag"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
